### ISSUE TITLE
Styles gets removed when reloading Page

### ISSUE THREAD

**Issue by paavo** [techdivision/ckstyles#17]
**Steps to reproduce:**
- Add a Style and publish the change
- Reload the Page

**What should happen:**
- The added style should not get lost. 

**What happens:**
- After reloading the Neos-Backend the Style-Class gets removed while loading the page. 
- After editing the Node again, the Property gets persisted without the style. 

**Versions**
_Neos: 5.3.1
Neos UI: 5.3.4
ckstyles: 1.1.1_

**Comment by masilikum** [comment]
Thank you for your input.
We experienced similar behavior when the value used as class contains whitespaces (e.g. "btn btn-primary"). I reopened the issue #5 to find a solution.
Does adjusting the class value fix the issue for you?

**Comment by SimonPaidla** [comment]
We have released a new version v1.1.3 where we fixed the issue with classes containing whitespaces.
Does this work for you?

**Comment by paavo** [comment]
works well, thanks @SimonPaidla
