### ISSUE TITLE
Remove the builded script, Maintenance

### ISSUE THREAD

**Issue by anianweber** [techdivision/ckstyles#30]
- Build the script on a release (with a GitHub Action?)
- Remove the builded script from this repository
- Bump Node version
- Bump dependencies

**Comment by dboeck** [comment]
Build the script on a release (with a GitHub Action?) && Remove the builded script from this repository

> Is not included, since it doesn't work with composer and GitHub Action

**Comment by dboeck** [comment]
https://github.com/techdivision/ckstyles/releases/tag/v1.5.0
