### ISSUE TITLE
CKEditor crashes in Neos 8.2

### ISSUE THREAD

**Issue by marvinenghardt** [techdivision/ckstyles#36]
From Neos version 8.2 on there is a javascript exception that prevents the CkEditor from being loaded. That unfortunately makes editing text in Neos impossible.

It happens on a freshly installed Neos 8.2 with the Neos.Demo site package, CkStyles installed and added presets.

The javascript error:
```
TypeError: Cannot call a class constructor without |new|
at — plugin.js:23
InlineStylesEditing — InlineStylesEditing.js:8
```
and:
```
plugincollection-load: It was not possible to load the plugin. Read more: https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-plugincollection-load
TypeError: 'arguments', 'callee', and 'caller' cannot be accessed in this context.
```

**Comment by crydotsnake** [comment]
We have the same issue but with: `BlockStyleEditing()`:

![SCR-20230109-ew8](https://user-images.githubusercontent.com/39345336/211279677-1e0a12d5-cf46-4937-b258-203d3ea38b30.png)

**Comment by mireo91** [comment]
> We have the same issue but with: `BlockStyleEditing()`:
> 
> ![SCR-20230109-ew8](https://user-images.githubusercontent.com/39345336/211279677-1e0a12d5-cf46-4937-b258-203d3ea38b30.png)

the same on my instance

**Comment by crydotsnake** [comment]
@mireo91 @marvinenghardt I've created a pull request that should fix the issue. It would be great if you could test this in your project! :)

**Comment by mireo91** [comment]
@crydotsnake i have tested your bugfix. Looks like everthing is working again
