### ISSUE TITLE
blockStyles not fully implemented

### ISSUE THREAD

**Issue by bweinzierl** [techdivision/ckstyles#9]
It is possible to configure blockStyles but doing so throws a js-error when using the dropdown to switch for example a paragraph style. (At least in Neos 5.1)

This Error can be fixed by changing `selection.getTopMostBlocks()` to `selection.getSelectedBlocks()` in file BlockStyleCommand.js on line 34

After this fix it is possible to apply classes to block level elements (the p-tag) but if you select the p-tag the dropdown does not display the corresponding style.
`const currentValue = this.props.formattingUnderCursor[`blockStyles:${this.props.presetIdentifier}`];` in `BlockStyleEditor.js` is null in that case. Any Ideas how to make this work? I would be willing to create a pull request for that if i can get it to work.

**Comment by regniets** [comment]
Thanks for the report, we know that this feature is not quite finished, but i will have a look into it!

**Comment by regniets** [comment]
https://github.com/techdivision/ckstyles/pull/10
